# ENTENDENDO A FUNÇÃO 'PRINT' - O PYTHON DIFERENCIA LETRAS MAIÚSCULAS DE MÍNUSCULAS - O CORRETO É print
print(23, 32) # OS NÚMEROS 23 E 32 SÃO "ARGUMENTOS NÃO NOMEADOS" PODE SER "ESPAÇO", "HÍFEN", "DOIS PONTOS"
#
print(32, 23, sep=":") # sep="" -> SÃO "ARGUMENTOS NOMEADOS" - NO CASO ESSA FUNÇÃO DEFINE QUAL SERÁ O SEPARADOR
#
print(23, 32, sep="-", end="Felps") # end="" -> DEFINE COMO SERÁ A QUEBRA DE LINHA "ENTER"
print(32, 23, sep=":", end='↨\n') # USAMOS \n ou \r\n PARA PULAR A LINHA "ENTER"
print(2332)
#
# A QUEBRA DE LINHA É UM COMANDO QUE EXISTE AUTOMATICAMENTE MAS NÃO VEMOS.
# QUEBRA DE LINHA -> CRLF = \r\n (COMANDO AUTOMÁTICO OCULTO)
# QUEBRA DE LINHA -> LF = \n (COMANDO AUTOMÁTICO OCULTO)
# PODEMOS USAR TANTO ASPAS DUPLAS ("") QUANTO INDIVIDUAIS ('')