# DEVEMOS TOMAR ALGUNS CUIDADOS COM A COPIA DE VALORES MUTAVEIS E IMUTAVEIS
# (=) PARA IMUTAVEIS -> DEFINE OU COPIA O VALOR DE UMA VARIAVEL PARA OUTRA
# (=) PARA MUTAVEIS -> COPIA O VALOR DA VARIAVEL QUE ESTÁ NA MEMORIA


# DEFINI O VALOR DA VARIAVEL 'IMUTAVEL 01' COMO 'FELIPE ANDRADE' E, COPIEI O VALOR DELA PARA A VARIAVEL 'IMUTAVEL 02'
imutavel_01 = 'Felipe Andrade'
imutavel_02 = imutavel_01

imutavel_01 = 'Felps'

# AGORA MESMO ALTERANDO O VALOR DA VARIAVEL 'IMUTAVEL 01', MINHA VARIAVEL 'IMUTAVEL 02' CONTINUA SENDO A COPIA ANTIGA
print(imutavel_01, imutavel_02) ### FELPS - FELIPE ANDRADE



# COM VALORES MUTAVEIS ISSO NÃO ACONTECE, ELE COPIA O VALOR QUE ESTÁ NA MEMORIA.
mutavel_01 = ['Felipe Andrade']
mutavel_02 = mutavel_01

mutavel_01[0] = ['Felps']

# COMO ALTEREI O ITEM DA LISTA 'MUTAVEL 01', ISSO ALTERA NA MEMORIA, ENTÃO A VARIAVEL 'MUTAVEL 02' TAMBÉM MUDARÁ.
print(mutavel_01, mutavel_02) ### FELPS - FELPS


# PARA ISSO NÃO ACONTECER, SE A INTENÇÃO FOR DEIXAR SALVO O VALOR DE UMA LISTA, UTILIZAMOS O COPY
mutavel_03 = ['Felipe']
mutavel_04 = mutavel_03.copy()

mutavel_03 = ['Felps']

print(mutavel_03, mutavel_04) ## FELPS - FELIPE